version: '3.8'

services:
  postgres:
    image: postgres:17
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
  api:
    build: .
    container_name: schedz
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/scheduler
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data: